apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crop-yield-ingress
  namespace: crop-yield
spec:
  ingressClassName: "haproxy"
  rules:
  - host: crop.dsvault.in
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: crop-yield-service
            port:
              number: 80
